# Generated by Django 4.1.7 on 2023-06-02 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('c_Name', models.CharField(max_length=100)),
                ('c_Gender', models.CharField(max_length=10)),
                ('c_Phone', models.CharField(max_length=10, unique=True)),
                ('c_Registration_Number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('c_Block', models.CharField(max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_SECRETKEY', models.CharField(default=uuid.UUID('16e6e123-3156-418d-9cd0-916fb0854e20'), editable=False, max_length=128, unique=True)),
                ('s_Name', models.CharField(max_length=100)),
                ('s_Gender', models.CharField(max_length=10)),
                ('s_Email', models.CharField(max_length=100, unique=True)),
                ('s_password', models.CharField(max_length=15)),
                ('s_Registration_Number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('s_Room_Number', models.CharField(max_length=10)),
                ('s_Block', models.CharField(max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
