# Generated by Django 4.1.7 on 2023-06-03 06:31

import RESTAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='c_SECRETKEY',
            field=models.CharField(default=RESTAPI.models.generate_auto_generated_field_value, max_length=25, unique=True),
        ),
    ]
