# Generated by Django 4.1.7 on 2023-06-02 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_SECRETKEY',
            field=models.CharField(default=uuid.UUID('c1b7a636-20f7-4c21-9dac-048fd6fcf74a'), editable=False, max_length=128, unique=True),
        ),
    ]
