# Generated by Django 4.1.7 on 2023-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0003_alter_student_s_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_SECRETKEY',
            field=models.CharField(default='ablRvwBSeuucZLEGTaJHzYQFF', max_length=128, unique=True),
        ),
    ]
