# Generated by Django 4.1.7 on 2023-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0003_cleaner_c_roomscleaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='c_RoomsCleaned',
            field=models.IntegerField(default=0),
        ),
    ]
