# Generated by Django 4.1.7 on 2023-06-02 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0004_alter_student_s_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_SECRETKEY',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
