# Generated by Django 4.1.7 on 2023-06-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0004_alter_cleaner_c_roomscleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_Already_Requested_Room_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomCleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('cleaner_ID', models.CharField(default='', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.student')),
            ],
        ),
    ]
