# Generated by Django 4.1.7 on 2023-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0005_alter_student_s_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_Registration_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_SECRETKEY',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
