# Generated by Django 4.1.7 on 2023-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0005_student_s_already_requested_room_clean_roomcleandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcleandata',
            name='date_completed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
