# Generated by Django 4.1.7 on 2023-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0006_alter_roomcleandata_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcleandata',
            name='date_completed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
