# Generated by Django 4.1.7 on 2023-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0006_alter_student_s_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_SECRETKEY',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
