# Generated by Django 4.1.7 on 2023-06-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0010_superuser_cleaner_c_type_cleaner_c_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaner',
            old_name='c_password',
            new_name='c_Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_password',
            new_name='s_Password',
        ),
    ]
