# Generated by Django 4.1.7 on 2023-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0011_rename_c_password_cleaner_c_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='c_Type',
            field=models.CharField(default='CLEANER', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_Type',
            field=models.CharField(default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='su_Type',
            field=models.CharField(default='SUPERUSER', max_length=10),
        ),
    ]
