# Generated by Django 4.1.7 on 2023-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0012_alter_cleaner_c_type_alter_student_s_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='c_Password',
            field=models.CharField(default='defaultpw', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_Password',
            field=models.CharField(max_length=100),
        ),
    ]
